export const COINS = [
    { symbol: "BTC", name: "Bitcoin" },
    { symbol: "ETH", name: "Ethereum" },
    { symbol: "XRP", name: "XRP" },
    { symbol: "SOL", name: "Solana" },
    { symbol: "BNB", name: "BNB" },
    { symbol: "DOGE", name: "Dogecoin" },
    { symbol: "ADA", name: "Cardano" },
    { symbol: "TRX", name: "TRON" },
    { symbol: "AVAX", name: "Avalanche" },
    { symbol: "LINK", name: "Chainlink" },
    { symbol: "DOT", name: "Polkadot" },
    { symbol: "LTC", name: "Litecoin" },
    { symbol: "BCH", name: "Bitcoin Cash" },
    { symbol: "XLM", name: "Stellar" },
    { symbol: "ATOM", name: "Cosmos" },
    { symbol: "NEAR", name: "NEAR" },
    { symbol: "APT", name: "Aptos" },
    { symbol: "ARB", name: "Arbitrum" },
    { symbol: "OP", name: "Optimism" },
    { symbol: "FIL", name: "Filecoin" },
    { symbol: "ALGO", name: "Algorand" },
    { symbol: "ETC", name: "Ethereum Classic" },
    { symbol: "UNI", name: "Uniswap" },
    { symbol: "AAVE", name: "Aave" },
    { symbol: "MKR", name: "Maker" },
    { symbol: "SUI", name: "Sui" },
    { symbol: "ICP", name: "Internet Computer" },
    { symbol: "HBAR", name: "Hedera" },
    { symbol: "VET", name: "VeChain" },
    { symbol: "MATIC", name: "Polygon" },
    { symbol: "PEPE", name: "Pepe" },
    { symbol: "SHIB", name: "Shiba Inu" },
];

export const TABS = [
    { id: "overview", label: "Overview" },
    { id: "news", label: "News" },
    { id: "chart", label: "Chart" },
];
